name: Scorecard

on:
  workflow_call:
    inputs:
      score-card-token:
        type: string
        description: GitHub token for Scorecard to use for publishing results
      publish-results:
        type: boolean
        description: Whether to publish results to OpenSSF REST API

permissions:
  contents: read

jobs:
  analysis:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      id-token: write
      security-events: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7  https://github.com/actions/checkout/commit/692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@62b2cac7ed8198b15735ed49ab1e5cf35480ba46 # v2.4.0 https://github.com/ossf/scorecard-action/commit/62b2cac7ed8198b15735ed49ab1e5cf35480ba46
        with:
          publish_results: true
          results_file: results.sarif
          results_format: sarif

      - name: Upload artifact
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.2 https://github.com/actions/upload-artifact/commit/84480863f228bb9747b473957fcc9e309aa96097
        with:
          path: results.sarif

      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@b8efe4dc6ab6d31abe3ec159420d2a4916880800 # v3.26.6 https://github.com/github/codeql-action/commit/b8efe4dc6ab6d31abe3ec159420d2a4916880800
        with:
          sarif_file: results.sarif
